<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LenowoTweeks</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="LenowoTweeks.en.json" />
    <EmbeddedResource Include="LenowoTweeks.en.json" LogicalName="LenowoTweeks.en.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ResoniteModLoader">
      <HintPath>../../../../../../../../../.nuget/packages/resonitemodloader/5.0.1/lib/net10.0/ResoniteModLoader.dll</HintPath>
    </Reference>
    <Reference Include="FrooxEngine" />
    <Reference Include="Elements.Core" />
    <Reference Include="SkyFrost.Base" />
    <Reference Include="0Harmony">
      <HintPath>../../../../../../../../../.nuget/packages/lib.harmony/2.4.2/lib/net10.0/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Renderite.Shared" />
    <Reference Include="Elements.Assets" />
    <Reference Include="ProtoFluxBindings" />
    <Reference Include="SkyFrost.Base.Models" />
  </ItemGroup>
</Project>